### ISSUE TITLE
Regarding gradle-witness

### ISSUE THREAD

**Issue by licaon-kter** [zoff99/ToxAndroidRefImpl#176]
Does this help? https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7268/diffs

/LE: eg. this builds fine FYI
```
  - versionName: 1.0.57
    versionCode: 10057
    commit: 1.0.57
    subdir: android-refimpl-app/app
    gradle:
      - yes
    srclibs:
      - gradlewitnessakwizgran@3119debde6c8aadebebcb0a7eb16dbb2e40c4046
    rm:
      - android-refimpl-app/gwitness/gwit/libs/gwitness.jar
    prebuild:
      - $ANDROID_HOME/tools/bin/sdkmanager 'cmake;3.6.4111459'
      - pushd $$gradlewitnessakwizgran$$
      - gradle build
      - popd
      - mv $$gradlewitnessakwizgran$$/build/libs/gradlewitnessakwizgran.jar ../gwitness/gwit/libs/gwitness.jar
      - sed -i -e '/gwitness.jar/d' witness.gradle
    scanignore:
      - android-refimpl-app/gwitness/gwit/libs/gwitness.jar
    ndk: r13b
```
